### ISSUE TITLE
Enhance the Navigation Bar with CSS for a Better User Experience

### ISSUE THREAD

**Issue by kambleprathamesh** [CSI-DMCE-2024/Ecommerce-Hacktoberfest2024#1]
![image](https://github.com/user-attachments/assets/25857e2f-f143-4a57-828b-afd421f3b910)

Enhance the navigation bar's CSS by adding transition effects and hover styles to improve user experience. This will make the navigation bar interactive and visually appealing.

**Comment by uzefaqureshi06** [comment]
can you assign this to me I will work on it

**Comment by YashBawari18** [comment]
hey leads i want to work on this issue

**Comment by tghosh294** [comment]
I want to work on this issue, assign me...

**Comment by Khanvilkarshravani27** [comment]
Hello Maintainer , Can I work on this issue?

**Comment by Mohit-Pawar** [comment]
Hey Maintainer, can I work on this issue?

**Comment by kambleprathamesh** [comment]
> hey leads i want to work on this issue

Yes Work on it

**Comment by Shreyashjadhav1001** [comment]
Hey maintainers, I want to work on this issue

**Comment by uzefaqureshi06** [comment]
can you assign this to me I want to work on this issue

**Comment by Aditya-jambhale** [comment]
> Hello maintainer, I would like to work on this task. Please assign me

Go for it and complete it asap
