### ISSUE TITLE
Design a User-Friendly "Page Not Found" (404) Error Page

### ISSUE THREAD

**Issue by kambleprathamesh** [CSI-DMCE-2024/Ecommerce-Hacktoberfest2024#2]
Create a visually appealing "Page Not Found" (404) page with custom messaging, guiding users back to the homepage or other sections of the site. Use simple elements like headings, text, and buttons, along with engaging styles and animations to make the experience user-friendly.

**Comment by NandaniThakur** [comment]
@kambleprathamesh, I want to work on this.

**Comment by uzefaqureshi06** [comment]
can you assign this to me I will work on it

**Comment by WIZARD138** [comment]
Hey Leads, can I work on this issue?

**Comment by Aditya-jambhale** [comment]
I want to contribute to this issue assign me

**Comment by Mohit-Pawar** [comment]
Hey Maintainers, can I work on this issue?

**Comment by Parth-code286** [comment]
Hey maintainer i want to work on this issue

**Comment by Apurva-29** [comment]
Hello maintainers I want to work on this issue

**Comment by Khanvilkarshravani27** [comment]
Hello Maintainer , Can I work on this issue?

**Comment by AdK819** [comment]
Hello Maintainers! Aditi here
May I work on this issue?

**Comment by kambleprathamesh** [comment]
> Hey Maintainers, can I work on this issue?

Yes

**Comment by YashBawari18** [comment]
Hello Maintainers, i want to work on this issue

**Comment by Shreyashjadhav1001** [comment]
Hello Maintainers, I want to work on this issue.

**Comment by TechMe103** [comment]
hello maintainers i would like to work on this plz assign to me this issue
