### ISSUE TITLE
Fix the image size and ensure that they are responsive

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Ecommerce-Hacktoberfest2024#25]
https://github.com/user-attachments/assets/aa3ed75a-ce17-441e-8758-b75bfafd3d50

upload your video or image  after fixing

**Comment by TechMe103** [comment]
can i work on this issue...? is only this vdo can be used or diff

**Comment by MiteshDalvi** [comment]
Please assign me this issue

**Comment by Shreyashjadhav1001** [comment]
Hello maintainers, I want to work on this issue.

**Comment by parthivsaikia** [comment]
Please assign me this issue. We can use contain the image in a div and give it a property of object-fit : cover so that they will be all of the same height and width.

**Comment by harshitkumargupta** [comment]
Hi @Aditya-jambhale, I request you to  Please assign me this isssue .

**Comment by Aditya-jambhale** [comment]
> can i work on this issue...? is only this vdo can be used or diff

just adjust the size of the images and make it responsive for mobile view and laptop view 
complete it asap

**Comment by Shreyashjadhav1001** [comment]
Hello maintainers, I want to work on this issue.

**Comment by Aditya-jambhale** [comment]
> Hello maintainers, I want to work on this issue.

Work on it and try complete ASAP
