### ISSUE TITLE
Fix the navbar links 

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Ecommerce-Hacktoberfest2024#26]
![Screenshot 2024-10-06 030008](https://github.com/user-attachments/assets/e2d2f734-821f-4d9f-84a3-6c4641205bdf)
upload your output

**Comment by TechMe103** [comment]
can i work on this issue

**Comment by devRoshan-25** [comment]
Hey maintainer , i want to work on this issue

**Comment by SanjanaSaw** [comment]
Hey maintainer , i want to work on this issue

**Comment by LokeshP03** [comment]
Hi Maintainers, can I work on this please?

**Comment by Aditya-jambhale** [comment]
> Hi Maintainers, can I work on this please?

work on it and complete it asap

**Comment by LokeshP03** [comment]
> > Hi Maintainers, can I work on this please?
> 
> work on it and complete it asap

Suree!

**Comment by MiteshDalvi** [comment]
can i work on this issue

**Comment by dexterousdhruv** [comment]
@Aditya-jambhale  I have created a pull request #31 wrt to the above issue. Please look into it and if it works for you, subsequently merge it. Sorry, for I didn't really wait to get assigned, I hope that's fine by you.

**Comment by LokeshP03** [comment]
I've fixed the issue and opened a PR, kindly request you to review it
Thanks in advance

**Comment by LokeshP03** [comment]
> > Hi Maintainers, can I work on this please?
> 
> work on it and complete it asap

I've fixed the issue and opened a PR, kindly request you to review it
Thanks in advance
