### ISSUE TITLE
Add GitHub Link and Social Media Icons to Footer.

### ISSUE THREAD

**Issue by im-amanjai** [CSI-DMCE-2024/Ecommerce-Hacktoberfest2024#33]
Subject: Request to Add GitHub Link and Social Media Icons to Footer

Hi,

I’ve observed that the website footer doesn’t include a link to the GitHub repository. Including this link would make it easier for visitors to access the repository. Additionally, adding icons for your social media handles would enhance the overall presentation. Thank you!

![Screenshot 2024-10-06 231128](https://github.com/user-attachments/assets/ac327312-4ff3-4972-ae69-eef1ad93fee5)

Could you please assign me this task under HacktoberFest2024? Thank you!

**Comment by ReshmaZore** [comment]
Hey Maintainer , I want to work on this issue

**Comment by uzefaqureshi06** [comment]
@im-amanjai  can you please please assign this issue to me i will make my best to do this project

**Comment by uzefaqureshi06** [comment]
can you plz assign this to me
