### ISSUE TITLE
Resolve the spanning issue of navbar

### ISSUE THREAD

**Issue by KUMUD-TECH** [CSI-DMCE-2024/Ecommerce-Hacktoberfest2024#34]
![Screenshot 2024-10-07 051123](https://github.com/user-attachments/assets/da5ea6c1-4e78-4164-a9a7-9bd5a542c863)

The current NavBar is not fixed to the PC window size.
I want to make it correct

Please assign this issue to me.

Add the Hacktoberfest label

Thank you

**Comment by ReshmaZore** [comment]
Hey maintainer, I would like to work on this issue

**Comment by uzefaqureshi06** [comment]
can you please please assign this issue to i will make my best

**Comment by uzefaqureshi06** [comment]
can you please please assign this issue i will make my best

**Comment by KUMUD-TECH** [comment]
can you pls state the reason of closing this issue
because on larger screen sizze navbar should be from left to right
