### ISSUE TITLE
Create a responsive  About us page for the website 

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Ecommerce-Hacktoberfest2024#37]
Try to add some information regarding the E-commerce website and make sure u follow the color code already used in the website

**Comment by Ritesh381** [comment]
@Aditya-jambhale I would like to work on this please assign me this issue

**Comment by Shaswat098** [comment]
please assign me this @Aditya-jambhale  I would like to work on this issue.

**Comment by TechMe103** [comment]
hey maintainer i want to work on this issue plz can u assign me this issue ????

**Comment by Aditya-jambhale** [comment]
> hey maintainer i want to work on this issue plz can u assign me this issue ????

go for it and complete it asap
