### ISSUE TITLE
Fix the products page create a responsive products page using sliders and cards 

### ISSUE THREAD

**Issue by Aditya-jambhale** [CSI-DMCE-2024/Ecommerce-Hacktoberfest2024#41]
Add products related to website

**Comment by sonigitkhushi** [comment]
Respected,
@Aditya-jambhale  please assign this issue to me.
Thank you

**Comment by ayush-sharaf** [comment]
please assign me this issue

**Comment by TechMe103** [comment]
hey maintainer can u assign me this issue?

**Comment by Thestoic3467** [comment]
Hii maintainer ! Would u please assign me this issue

**Comment by TechMe103** [comment]
Hey maintainer can I work on this issue?

**Comment by Pranav-Singh-Devloper** [comment]
Hello maintainer,
This would be my first contribution in the open source world 
Can I work on this issue?
i won't disappoint you

**Comment by Aditya-jambhale** [comment]
> Hii maintainer ! Would u please assign me this issue

go for it

**Comment by YashBawari18** [comment]
hey maintainer , please assign me this issue

**Comment by ghost** [comment]
> > Hii maintainer ! Would u please assign me this issue
> 
> go for it

Done it
