### ISSUE TITLE
#Buttons Not Linking to "Athletes Choice"Social Media Accounts

### ISSUE THREAD

**Issue by prakruthiprasad20** [CSI-DMCE-2024/Ecommerce-Hacktoberfest2024#47]
Buttons Not Linking to "Athletes Choice" Accounts

The buttons intended to link to the "Athletes Choice" workout clothing social media accounts are currently not functioning. Users are unable to click and access the respective account URLs.

**Comment by sajithcode** [comment]
@prakruthiprasad20  provide Athletes Choice links and assign me this work
