### ISSUE TITLE
Enhance the Appearance of the Footer Section

### ISSUE THREAD

**Issue by kambleprathamesh** [CSI-DMCE-2024/Ecommerce-Hacktoberfest2024#5]
![image](https://github.com/user-attachments/assets/c36e112e-76fe-4b97-bf86-d8bdfde15526)

Enhance the footer section by applying more effective CSS styling. Focus on using contrasting colors, improved typography, and adequate spacing to create a visually appealing layout that draws attention and improves overall aesthetics.

**Comment by NandaniThakur** [comment]
@kambleprathamesh I want to work on this

**Comment by uzefaqureshi06** [comment]
can you assign this to me I will work on it

**Comment by SanjanaSaw** [comment]
can i work on this issue?

**Comment by SanjanaSaw** [comment]
Hey leads i want to work on this issue.

**Comment by tghosh294** [comment]
I can work on this one, assign me

**Comment by uzefaqureshi06** [comment]
can you assign this to me I will work on it

**Comment by Parth-code286** [comment]
Hey maintainer i want to work on this issue

**Comment by Khanvilkarshravani27** [comment]
Hello Maintainer , Can I work on this issue?

**Comment by Mohit-Pawar** [comment]
Hey Maintainer, can I work on this issue?

**Comment by kambleprathamesh** [comment]
> Hey leads i want to work on this issue.

Yess Continue Working!

**Comment by devRoshan-25** [comment]
Hey maintainer , i want to work on this issue
