### ISSUE TITLE
### enhance better css ,do better ui of the website 

### ISSUE THREAD

**Issue by REHAN-18** [CSI-DMCE-2024/Ecommerce-Hacktoberfest2024#57]
" lacks proper design elements, CSS styling, and functional features, resulting in a suboptimal user experience. This issue aims to outline key enhancements needed to improve the overall appearance and functionality of the site.

i. Layout and Structure:
ii. Color Scheme:
<img width="1429" alt="Screenshot 2024-10-15 at 11 28 20 AM" src="https://github.com/user-attachments/assets/849f304d-9d75-4140-b249-21dab717889c">

## even the menu are not align proper improve pls assign

**Comment by AadishSanghai** [comment]
@Aditya-jambhale   i would like to work on this issue can you please assign me this work and also please add hactoberfest tag on this issue.

**Comment by Parth-code286** [comment]
Hey maintainer I want to work on this issue
