### ISSUE TITLE
FEATURE: Link App Store and Play Store images to their Websites  #92

### ISSUE THREAD

**Issue by DEEP-666** [CSI-DMCE-2024/Ecommerce-Hacktoberfest2024#58]
Adding a link to the images of AppStore and Google Play Store would be a Good feature.

So that User Can Directly redirect to AppStore or Google Play store to Download Application.

 
![Screenshot 2024-10-16 072242](https://github.com/user-attachments/assets/ab5b0a31-6bea-4b2e-8ab9-d2fa7f311861)

**Comment by DEEP-666** [comment]
#92

I link the images with website of play store and app store ,so it is easier for user to download.
And once the app listed on Play Store and App Store we can update the link.

**Comment by YashBawari18** [comment]
Hello Maintainers , i want to work on this issue

**Comment by AadishSanghai** [comment]
@Aditya-jambhale   i would like to work on this issue can you please assign me this work and also please add hactoberfest tag on this issue.

**Comment by DEEP-600** [comment]
Hello Maintainer,
is this issue is not helpfull?
