### ISSUE TITLE
Enhance Website Responsiveness for Optimal User Experience

### ISSUE THREAD

**Issue by kambleprathamesh** [CSI-DMCE-2024/Ecommerce-Hacktoberfest2024#7]
Improve the website's responsiveness to ensure it looks and functions well on all devices. Use flexible layouts, media queries, and optimized images to provide a seamless experience for users on desktops, tablets, and mobile devices.

![image](https://github.com/user-attachments/assets/59be0df4-dd9b-4265-abf7-5be0e52f1979)
![image](https://github.com/user-attachments/assets/7ba6d7b7-8ebc-44c0-b1e6-7172bc70887b)

**Comment by uzefaqureshi06** [comment]
can you assign this to me I will work on it

**Comment by GrandPredator** [comment]
can you assign this to me i will work on it

**Comment by Parth-code286** [comment]
Hey maintainer i want to work on this issue

**Comment by Mohit-Pawar** [comment]
Hey Maintainer, can I work on this issue?

**Comment by kambleprathamesh** [comment]
> hey leads,can you assign this to me i will work on it

Yes  You Can Work!
